### PR TITLE
Fix variable names in stage_multiatlas_vote of stages.sh

### PR DESCRIPTION
**Pull request by cbedetti**
Fix issue #82

### CODE REVIEW

**Comment by gdevenyi** [comment]
Did this actually fix it? :)

**Comment by cbedetti** [comment]
Yes, it worked with on my data of the issue.
I even tested with a fresh input directory. Jobs were correctly submitted.
I could wait for them to finish if you want.

**Comment by gdevenyi** [comment]
Please report back when things finish up :+1:

**Comment by gdevenyi** [comment]
Did this change fix your run?

**Comment by cbedetti** [comment]
I have relaunch some test. All `register_atlas_template` worked, the last one ran on Thursday 15th. Since then, this is the status on scinet:

```
gpc-sched-ib0: 
                                                                                  Req'd    Req'd       Elap
Job ID                  Username    Queue    Jobname          SessID  NDS   TSK   Memory   Time    S   Time
----------------------- ----------- -------- ---------------- ------ ----- ------ ------ --------- - ---------
42797554.gpc-sched-ib0  cbedetti    batch_ib T2017-06-14_14-5    --      1      8    --   04:00:00 Q       -- 
42797555.gpc-sched-ib0  cbedetti    batch_ib T2017-06-14_14-5    --      1      8    --   04:00:00 H       -- 
```

**Pull request merged**
